### ISSUE TITLE
Cannot logout

### ISSUE THREAD

**Issue by lerminou** [sdiaz/FOSRestBundleByExample#14]
i try to build a simple rest api with your project.
generate token is ok, view users is ok, all is ok but i can't logout.

when i go to /security/token/destroy i have in the return 200 logout succesfully, but if i try to view users, i can with code 200 OK.. so the logout doesn't work, or i don't know how it works

Can you help me ?

**Comment by sdiaz** [comment]
A token is valid during it's lifecycle, you set the expiration time on security.yml. I have updated the project so the approach is different.
