### ISSUE TITLE
Images in documentation not loading

### ISSUE THREAD

**Issue by vigilant8** [sdiaz/FOSRestBundleByExample#15]
The images (screenshots) in documentation do not load such as: https://dl.dropbox.com/u/3972728/github/devhttpclient01.png
https://dl.dropbox.com/u/3972728/github/devhttpclient02.png

Could you please upload them so we could really understand the example?

Thank you.

**Comment by sdiaz** [comment]
I have updated the whole project to 2.6 and refactor the entire bundle, since I created it many years ago. I will check the documents and update them
